services:
  nginx:
    build: .docker/nginx
    container_name: nginx_mkcert
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN:-onepage.local}
      - DOLLAR=${DOLLAR:-$}
    volumes:
      - ./public:/usr/share/nginx/html:ro
    restart: unless-stopped